version: '2'
services:
    arango:
        image: arangodb:latest
        environment:
          ARANGO_ROOT_PASSWORD: sae073L&%
          #ports:
          #- 8529:8529
        volumes:
          - arangodb_data_container:/var/lib/arangodb3
          - arangodb_apps_data_container:/var/lib/arangodb3-apps
        restart: always
        mem_limit: 1g
        networks:
            - nginx_default
              
    node:
        build: node/.
        command: npm start
        #depends_on: 
        mem_limit: 64m
        volumes:
            - ./node/:/node
            - ./node/node_modules:/node/node_modules
        restart: always
        networks:
            - nginx_default


volumes:
  arangodb_data_container:
  arangodb_apps_data_container:
networks:
    nginx_default:
        external: true
